apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-backup
  name: mongodb-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-backup
  strategy: {}
  template:
    metadata:
      labels:
        app: mongodb-backup
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: rclone
        resources: {}
status: {}
